### ISSUE TITLE
Nothing happens when right clicking a chest with the sell wand

### ISSUE THREAD

**Issue by astirling** [DNx5/QuickSellWand#2]
Server version: Paper version git-Paper-317 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
QSW version: QuickSellWand v1.0.3-SNAPSHOT

Can give the wand now (much thanks), but when I right click (tried left also) on a chest, trapped chest, or ender chest to sell items, nothing happens.  There are no messages in the chat window or server console.

The permission quicksellwand.use is given directly to the player.

**Comment by DNx5** [comment]
Hi, sorry for slow response, you could add me on discord if it urgent. Coppélia#3817

**Comment by astirling** [comment]
It's not urgent, but I wanted to record it.  I'm Magarathin#9751 on Discord.  I sent a friends request if you wanted to discuss it there.

**Comment by DNx5** [comment]
Thank you
